### ISSUE TITLE
Instructions for more/all liboqs algorithms support (KEMs and signature)

### ISSUE THREAD

**Issue by pqfan** [microsoft/PQCrypto-VPN#21]
Kevin,
[Within this link](https://github.com/open-quantum-safe/openssl/wiki/Using-liboqs-algorithms-that-are-not-in-the-forks) I found that there are instructions on how to implement at code/compile-level those liboqs algorithms you want, who are not (currently) included in the oqs-openssl forks. There seem to be two ways to achieve that. I propose for the full liboqs list support of algorithms (KEMs and signatures) so those interested may have the widest possible range of options and ability to test the algorithms.

Also I confirm that I have tested all the oqs-openssl signature schemes and all of them are working on my Windows build (which is the exact latest since I am always checking the devel repo for updates)

It would be great if you would implement the total range of algorithms, in the end, the more the options the better the cryptography result. Please let us know of your thoughts on this possibility.

Best regards!

**Comment by kevinmkane** [comment]
Please do share your testing results with the OQS team, first and foremost, and thank you for making the effort!

Once the next release of liboqs is done, the OQS team will be expanding coverage at the OpenSSL layer to cover the remaining algorithms. So what you want is already planned. And when that OpenSSL release is finished, we'll update to their releases and make our release, at which point everything should be available.
