### ISSUE TITLE
OpenVPN version update?

### ISSUE THREAD

**Issue by ReverseControl** [microsoft/PQCrypto-VPN#22]
The project update to integrate with the latest OpenSSL is great step forward. Is there any roadmap to update the OpenVPN side to the latest version as well?

Thanks.

**Comment by kevinmkane** [comment]
The update to OpenVPN 2.4.9 was already done in commit a361f9aa91af6e81393a73e734707607ef6b1e93 on the `dev-1.3` branch.

We haven't yet updated to the latest liboqs and OQS-OpenSSL in this branch yet. I have a branch where I'm doing verification builds as they make updates, but we won't update to this in `dev-1.3` until OQS declares their release done.
