### ISSUE TITLE
Compatibility with OQS-OpenSSL_1_1_1 branch of openssl

### ISSUE THREAD

**Issue by lrubens** [microsoft/PQCrypto-VPN#24]
Are there any updates on integrating OpenSSL 1.1.1? Are there compatibility issues? I am currently working on integrating one of the PQ algorithms into this project; however, it was built on the OQS-OpenSSL_1_1_1 branch.

**Comment by kevinmkane** [comment]
We're waiting on OQS to officially announce their 1.1.1 release before we do our next release, but the `dev-1.3` branch is currently up to date with the latest release of liboqs and rc0 of OQS-OpenSSL 1.1.1. We had a couple small issues to work around but that's been done. Check the updated README.md in that branch for cloning and build instructions if you want to take a look at it.
