### ISSUE TITLE
sidhp751 crash - linux

### ISSUE THREAD

**Issue by pqfan** [microsoft/PQCrypto-VPN#27]
Kevin,
Since a while ago (since the dev-1.3 testing started or so) I would like to report that PQCrypto-VPN seems to crash when sidhp751 is used as KEM. This occurs in the linux built if I have observed correctly.

Thanks in advance

**Comment by kevinmkane** [comment]
Please provide more information about your crash to help us assess the issue. Please indicate the exact versions you're using, especially if this is with a newer version of liboqs than we're currently based on, configuration files, log file outputs, and repro steps that lead to the crash, and any other information that may be useful. Then we'll be able to investigate. Thanks!

**Comment by pqfan** [comment]
I am not sure if this happens due to specific post-quantum type keys used or is a fault in the algorithm implementation... Whatever there was just released a fix at the liboqs for SIKE possible solving this issue, going to check and get back for more information as you requested, or otherwise will close the issue.

**Comment by pqfan** [comment]
No it is still not working... I am using a CA of the Sphincs (the haraka 128 bit robust) type and as Server and Client certificates I picked up Rainbow-Vc (Classic). Also I have applied passwords to the certificates and enabled password authentication along with the certificate authentication. Finally, the crash seems to happen in the Windows version, my (previously made) mistake.

**Comment by pqfan** [comment]
Also I should state that I use a custom PQCrypto-VPN with liboqs 0.4.0 and openssl-oqs latest release

**Comment by kevinmkane** [comment]
Any issues integrating with liboqs 0.4.0 will have to wait until we begin work on updating to that version, if they're not present in our official release with 0.3.0. If you figure out any more details of what's happening, do please share them for our future reference.

**Comment by pqfan** [comment]
Sure Kevin, 
I just rebuilt a custom PQCrypto-VPN with liboqs 0.4.0 from ds-sync-pqclean branch and openssl-oqs latest and rechecked launching a PQ VPN of the sidhp610 KEM type with falcon1024 as all cert types and password protected authentication of the 256 bit type (so I can assure at least 256 bits of PQ security if I have understood the whole mechanism well)
On the Windows edition only, sidhp751 crashed provided a memory allocation failure error but from sidhp610 and below it now seems to work smoothly and quickly. Keep that in your records.

**Comment by kevinmkane** [comment]
Updating to 0.4.0 is tracked under #26; we can refer back to this information later, so closing this issue.
