### ISSUE TITLE
Build failure at step 1.

### ISSUE THREAD

**Issue by ReverseControl** [microsoft/PQCrypto-VPN#7]
Error message:

```
docker build -t vpn_microsoft_test .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM ubuntu:19.10
 ---> 4f82834f04c6
Step 2/5 : WORKDIR /tmp
 ---> Using cache
 ---> c7c7524a447f
Step 3/5 : RUN apt update && apt install -y git gcc cmake make python
 ---> Using cache
 ---> 7eb2fb99e108
Step 4/5 : RUN git clone https://github.com/microsoft/PQCrypto-VPN.git
 ---> Running in 11898c70764e
Cloning into 'PQCrypto-VPN'...
Removing intermediate container 11898c70764e
 ---> 492e553a7b01
Step 5/5 : RUN cd /tmp/PQCrypto-VPN/openvpn/build && python build.py
 ---> Running in 01de9c40f600
fatal: Remote branch OpenSSL_1_0_2-stable not found in upstream origin
Cloning openssl ...
***** Running command: git clone -q --branch OpenSSL_1_0_2-stable https://github.com/open-quantum-safe/openssl openssl-oqs
Traceback (most recent call last):
  File "build.py", line 258, in <module>
    build_oqs_openssl()
  File "build.py", line 121, in build_oqs_openssl
    git_clone(OPENSSL_OQS_REPO, OPENSSL_OQS_BRANCH, 'openssl-oqs', OPENSSL_OQS_COMMIT)
  File "build.py", line 74, in git_clone
    os.chdir(local_name)
OSError: [Errno 2] No such file or directory: 'openssl-oqs'
The command '/bin/sh -c cd /tmp/PQCrypto-VPN/openvpn/build && python build.py' returned a non-zero code: 1

```

Dockerfile to reproduce error:

```
FROM ubuntu:19.10

WORKDIR /tmp

RUN apt update && apt install -y git gcc cmake make python
RUN git clone https://github.com/microsoft/PQCrypto-VPN.git 

RUN cd /tmp/PQCrypto-VPN/openvpn/build && python build.py
```

I modified the build.py script quiet a bit to get past several errors, but they just keep coming. Could someone please update the build system for this repo so that it actually builds on the first try. There have many changes in OQS OpenSSL and it breaks everything.

**Comment by kevinmkane** [comment]
Thanks for bringing this to our attention.

The immediate problem appears to be at some point after our release, OQS changed the name of the 1.0.2 branch to `OQS-OpenSSL_1_0_2-stable`. This problem should be fixable by changing `OPENSSL_OQS_BRANCH` in `build.py` to be this value. I'll prepare and test an update to fix this, but you can try this yourself in the meantime, if you like.

Our build system also does not attempt to build with the current head of the OpenSSL branch. At the time we were developing PQCrypto-VPN, the OQS-OpenSSL branch itself in development and was moving quickly, and it was not practical for us to try and always remain compatible with the head of the branch. Therefore our build system also picks out a particular commit we know to be working with our code. 

Although that branch is no longer under active development, OQS has deprecated the 1.0.2 branch in favor of the 1.1.1 branch. As a result we've decided not update the current version of PQCrypto-VPN to work with the 1.0.2 branch head. Instead, we're working with the OQS team on their 1.1.1 fork to get it ready and usable, and we will then update PQCrypto-VPN. Our next release of PQCrypto-VPN will both take in the latest updates from OpenVPN, and also switch to the 1.1.1 branch of OQS-OpenSSL, as it will have the most up-to-date versions of the algorithms and will support TLS 1.3.

**Comment by kevinmkane** [comment]
Sorry, it appears OQS didn't just rename their branch, they started from scratch so the checkpoint commit we were using before no longer exists in their repo. This will take a little longer to work out.

**Comment by kevinmkane** [comment]
My fork of OQS's OpenSSL repo still had the right commits, so we can use that for now until our next release to fix this issue. See #8.
