### ISSUE TITLE
branch: oqsrepo Build Error

### ISSUE THREAD

**Issue by ReverseControl** [microsoft/PQCrypto-VPN#9]
The error:

```
Traceback (most recent call last):
  File "build.py", line 270, in <module>
    build_openvpn_linux()
  File "build.py", line 185, in build_openvpn_linux
    shutil.copy('../oqs-openssl-output/openssl/lib/libcrypto.so.1.0.0', stagepath + '/' + OPENVPN_LINUX_PREFIX + '/lib')
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/opt/PQCrypto-VPN/openvpn/build/scratch/stage//usr/local/openvpn/lib'
The command '/bin/sh -c cd /opt/PQCrypto-VPN/openvpn/build && python build.py' returned a non-zero code: 1
```
This is a simple error to fix, but after I fix it more errors just keep coming. If you look at "'/opt/PQCrypto-VPN/openvpn/build/scratch/stage//usr/local/openvpn/lib'" it has two forward slashes instead of one. Please take a look.

Dockerfile:

```
FROM ubuntu:19.10

RUN apt update && apt install -y \
        liblz4-dev               \
        liblzo2-dev              \
        libpam-dev               \
        libssl-dev               \
        libtool                  \
        libtool-bin              \
        cmake                    \
        make                     \
        autoconf                 \
        python                   \
        git

RUN cd /opt && git clone --branch oqsrepo https://github.com/microsoft/PQCrypto-VPN.git
RUN cd /opt/PQCrypto-VPN/openvpn/build && python build.py
```

I should mention that python3 has the built in path module in pathlib which handles path independent of operating system. If the build script is ever ported to python 3, path error of this kind can be avoided all together.

**Edit 1:**  The "oqsrepo" branch was merged into master at commit 1d358944dbe0e4483a578aa141d3772a096423dd for future reference.

**Comment by kevinmkane** [comment]
I'm surprised the two forward slashes ends up being a problem. This doesn't happen on my Ubuntu 18.04 build VM. #8 fixes the build problem there with the OQS-OpenSSL repo and I get a successful build, so I'm going to merge that fix.

I'll then look at reproducing your error in a container per your instructions to see what's causing those problems. Depending on the cause and how much work will be required to do a fix will determine if I can put a fix up sooner, or if it'll have to wait and get done with our next release.

Thanks again for the reports!

**Comment by ReverseControl** [comment]
I tested with Docker base image ubuntu:18.04 and the issue is the same:

```
Cloning openvpn ...
***** Running command: git clone -q --branch pqcrypto https://github.com/Microsoft/openvpn openvpn-pq
***** Running command: autoreconf -i -f -v
Traceback (most recent call last):
  File "build.py", line 270, in <module>
    build_openvpn_linux()
  File "build.py", line 185, in build_openvpn_linux
    shutil.copy('../oqs-openssl-output/openssl/lib/libcrypto.so.1.0.0', stagepath + '/' + OPENVPN_LINUX_PREFIX + '/lib')
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/opt/PQCrypto-VPN/openvpn/build/scratch/stage//usr/local/openvpn/lib'
The command '/bin/sh -c cd /opt/PQCrypto-VPN/openvpn/build && python build.py' returned a non-zero code: 1

```

Dockerfile:

```
FROM ubuntu:18.04

RUN apt update && apt install -y \
        liblz4-dev               \
        liblzo2-dev              \
        libpam-dev               \
        libssl-dev               \
        libtool                  \
        libtool-bin              \
        cmake                    \
        make                     \
        autoconf                 \
        python                   \
        git

#Note: oqsrepo merge into master commit: 1d35894
RUN cd /opt && \
        git clone https://github.com/microsoft/PQCrypto-VPN.git && \
        cd PQCrypto-VPN                                        && \
        git checkout 1d35894    

RUN cd /opt/PQCrypto-VPN/openvpn/build && python build.py

```

**Comment by kevinmkane** [comment]
Very curious. I'll check it out.

**Comment by kevinmkane** [comment]
The double forward slash wasn't actually an issue. The issue there was not all of the needed directories were being created ahead of time, so file operations to place files in them were failing.

It turns out we also rely on a few other command line utilities that are standard on typical Ubuntu installs but are not present in the Docker image.

The script will now skip the Windows build without failure if the Windows-built OQS-OpenSSL DLL's aren't present. At the point where we snapped their tree, OQS-OpenSSL for Windows couldn't be cross-compiled on Linux.

See #10.

**Comment by ReverseControl** [comment]
Great. That works! ( That is, #10  fixes all the issues for building.)
